In [1]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns


In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

df = pd.read_csv("C:/Users/rudal/OneDrive/Ai/Seed_data.csv", header=0)
df


A      P       C     LK     WK  A_Coef    LKG  target
0    15.26  14.84  0.8710  5.763  3.312   2.221  5.220       0
1    14.88  14.57  0.8811  5.554  3.333   1.018  4.956       0
2    14.29  14.09  0.9050  5.291  3.337   2.699  4.825       0
3    13.84  13.94  0.8955  5.324  3.379   2.259  4.805       0
4    16.14  14.99  0.9034  5.658  3.562   1.355  5.175       0
..     ...    ...     ...    ...    ...     ...    ...     ...
205  12.19  13.20  0.8783  5.137  2.981   3.631  4.870       2
206  11.23  12.88  0.8511  5.140  2.795   4.325  5.003       2
207  13.20  13.66  0.8883  5.236  3.232   8.315  5.056       2
208  11.84  13.21  0.8521  5.175  2.836   3.598  5.044       2
209  12.30  13.34  0.8684  5.243  2.974   5.637  5.063       2

[210 rows x 8 columns]

In [5]:
df.isnull().sum()


A         0
P         0
C         0
LK        0
WK        0
A_Coef    0
LKG       0
target    0
dtype: int64

In [6]:
# 특성과 타겟 분리
X = df.drop('target', axis=1)  # 특성
y = df['target']               # 타겟

# StandardScaler를 사용하여 데이터 스케일링
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 스케일링된 데이터로 데이터프레임 생성
df_scaled = pd.DataFrame(X_scaled, columns=X.columns)
df_scaled

A         P         C        LK        WK    A_Coef       LKG
0    0.142098  0.215462  0.000061  0.304218  0.141702 -0.986152 -0.383577
1    0.011188  0.008224  0.428515 -0.168625  0.197432 -1.788166 -0.922013
2   -0.192067 -0.360201  1.442383 -0.763637  0.208048 -0.667479 -1.189192
3   -0.347091 -0.475333  1.039381 -0.688978  0.319508 -0.960818 -1.229983
4    0.445257  0.330595  1.374509  0.066666  0.805159 -1.563495 -0.475356
..        ...       ...       ...       ...       ...       ...       ...
205 -0.915515 -1.043321  0.309736 -1.112048 -0.736716 -0.046135 -1.097413
206 -1.246235 -1.288937 -0.844122 -1.105261 -1.230328  0.416540 -0.826156
207 -0.567571 -0.690247  0.733948 -0.888070 -0.070604  3.076588 -0.718060
208 -1.036090 -1.035645 -0.801701 -1.026077 -1.121521 -0.068135 -0.742535
209 -0.877620 -0.935864 -0.110235 -0.872233 -0.755292  1.291223 -0.703784

[210 rows x 7 columns]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)


In [16]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression


In [17]:
# Build a decision tree classifier and predict

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))



--- Decision Tree Classifier ---
0.9056603773584906
[[15  0  2]
 [ 3 18  0]
 [ 0  0 15]]


In [18]:
# Build a logistic regression classifier and predict

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))



--- Logistic Regression Classifier ---
0.9056603773584906
[[15  1  1]
 [ 3 18  0]
 [ 0  0 15]]


C:\Users\rudal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [19]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Radom Forest ---
0.9622641509433962
[[17  0  0]
 [ 2 19  0]
 [ 0  0 15]]
